# Generated by Django 6.1.1 on 2026-09-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('wake_time', models.DateTimeField(blank=True, null=True)),
                ('sleep_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
